parameters:
    base.service.class: Fuz\QuickStartBundle\Base\BaseService
    quickstart.locale.listener.class: Fuz\QuickStartBundle\EventListener\LocaleListener
    quickstart.last_route.listener.class: Fuz\QuickStartBundle\EventListener\LastRouteListener
    quickstart.routing.class: Fuz\QuickStartBundle\Services\Routing

services:

    base.service:
        class: %base.service.class%
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]

    quickstart.locale.listener:
        class: '%quickstart.locale.listener.class%'
        arguments:
            - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }

    quickstart.last_route.listener:
        class: '%quickstart.last_route.listener.class%'
        arguments:
            - '@quickstart.routing'
        tags:
            - { name: kernel.event_subscriber }

    quickstart.routing:
        class: '%quickstart.routing.class%'
        arguments:
            - '@router'

